// src/app/jobs/components/jobData.js

export const jobs = [
    {
      id: 1,
      title: "Senior Software Engineer",
      company: "ABC Tech",
      location: "Hyderabad",
      salary: "₹8-15 LPA",
      experience: "3-6 Years",
      industry: "IT & Software",
      type: "Full-time",
      department: "Software Development",
      posted: "2 days ago",
      skills: ["React", "Node.js", "MongoDB"],
      description:
        "Full-time position for experienced software engineer to build scalable web applications.",
      companyLogo: "/images/company-logos/abc-tech.png",
      rating: 4.2,
    },
    {
      id: 2,
      title: "Data Scientist",
      company: "XYZ Analytics",
      location: "Bangalore",
      salary: "₹10-20 LPA",
      experience: "2-5 Years",
      industry: "IT & Software",
      type: "Full-time",
      department: "Research & Development",
      posted: "3 days ago",
      skills: ["Python", "TensorFlow", "SQL"],
      description: "Analyze large datasets to drive business decisions.",
      companyLogo: "/images/company-logos/xyz-analytics.png",
      rating: 4.5,
    },
    {
      id: 3,
      title: "HR Manager",
      company: "Global Corp",
      location: "Mumbai",
      salary: "₹6-12 LPA",
      experience: "5-8 Years",
      industry: "HR & Recruitment",
      type: "Full-time",
      department: "HR",
      posted: "1 day ago",
      skills: ["Recruitment", "Employee Relations", "Payroll"],
      description: "Manage HR operations and employee engagement.",
      companyLogo: "/images/company-logos/global-corp.png",
      rating: 4.0,
    },
    {
      id: 4,
      title: "Marketing Specialist",
      company: "BrandBuzz",
      location: "Delhi",
      salary: "₹5-10 LPA",
      experience: "1-3 Years",
      industry: "Sales & Marketing",
      type: "Part-time",
      department: "Marketing",
      posted: "4 days ago",
      skills: ["SEO", "Content Marketing", "Social Media"],
      description: "Develop and execute marketing campaigns.",
      companyLogo: "/images/company-logos/brandbuzz.png",
      rating: 3.8,
    },
    {
      id: 5,
      title: "Financial Analyst",
      company: "MoneyWise",
      location: "Chennai",
      salary: "₹7-14 LPA",
      experience: "3-5 Years",
      industry: "Finance & Accounting",
      type: "Full-time",
      department: "Finance and Accounts",
      posted: "2 days ago",
      skills: ["Excel", "Financial Modeling", "Budgeting"],
      description: "Analyze financial data and prepare reports.",
      companyLogo: "/images/company-logos/moneywise.png",
      rating: 4.3,
    },
    {
      id: 6,
      title: "Operations Manager",
      company: "LogiTech",
      location: "Pune",
      salary: "₹9-18 LPA",
      experience: "5-8 Years",
      industry: "Operations",
      type: "Contract",
      department: "Operations",
      posted: "5 days ago",
      skills: ["Supply Chain", "Process Optimization", "Team Management"],
      description: "Oversee operational efficiency and team performance.",
      companyLogo: "/images/company-logos/logitech.png",
      rating: 4.1,
    },
    {
      id: 7,
      title: "Customer Support Executive",
      company: "HelpDesk Inc.",
      location: "Kolkata",
      salary: "₹3-6 LPA",
      experience: "0-1 Years",
      industry: "Customer Support",
      type: "Part-time",
      department: "Customer Support",
      posted: "3 days ago",
      skills: ["Communication", "Problem Solving", "CRM"],
      description: "Provide excellent customer service and support.",
      companyLogo: "/images/company-logos/helpdesk.png",
      rating: 3.9,
    },
    {
      id: 8,
      title: "Retail Store Manager",
      company: "ShopEasy",
      location: "Ahmedabad",
      salary: "₹4-8 LPA",
      experience: "2-5 Years",
      industry: "Retail",
      type: "Full-time",
      department: "Sales",
      posted: "6 days ago",
      skills: ["Sales", "Inventory Management", "Customer Service"],
      description: "Manage retail store operations and sales.",
      companyLogo: "/images/company-logos/shopeasy.png",
      rating: 4.0,
    },
    {
      id: 9,
      title: "Civil Engineer",
      company: "BuildWell",
      location: "Jaipur",
      salary: "₹6-12 LPA",
      experience: "3-6 Years",
      industry: "Construction",
      type: "Temporary",
      department: "Engineering",
      posted: "2 days ago",
      skills: ["AutoCAD", "Project Management", "Structural Analysis"],
      description: "Design and oversee construction projects.",
      companyLogo: "/images/company-logos/buildwell.png",
      rating: 4.2,
    },
    {
      id: 10,
      title: "Legal Advisor",
      company: "LawFirm",
      location: "Lucknow",
      salary: "₹8-15 LPA",
      experience: "5-8 Years",
      industry: "Legal",
      type: "Remote",
      department: "Legal",
      posted: "4 days ago",
      skills: ["Contract Law", "Compliance", "Negotiation"],
      description: "Provide legal advice and support to clients.",
      companyLogo: "/images/company-logos/lawfirm.png",
      rating: 4.4,
    },
    {
      id: 11,
      title: "Content Writer",
      company: "MediaHouse",
      location: "Indore",
      salary: "₹3-7 LPA",
      experience: "1-3 Years",
      industry: "Media",
      type: "Internship",
      department: "Public Relations",
      posted: "3 days ago",
      skills: ["Writing", "Editing", "SEO"],
      description: "Create engaging content for various platforms.",
      companyLogo: "/images/company-logos/mediahouse.png",
      rating: 3.7,
    },
    {
      id: 12,
      title: "Hotel Manager",
      company: "StayLux",
      location: "Chandigarh",
      salary: "₹5-10 LPA",
      experience: "3-5 Years",
      industry: "Hospitality",
      type: "Freelance",
      department: "Administration",
      posted: "5 days ago",
      skills: ["Hospitality Management", "Customer Service", "Budgeting"],
      description: "Manage hotel operations and guest satisfaction.",
      companyLogo: "/images/company-logos/staylux.png",
      rating: 4.0,
    },
    {
      id: 13,
      title: "Logistics Coordinator",
      company: "FreightFast",
      location: "Coimbatore",
      salary: "₹4-9 LPA",
      experience: "2-4 Years",
      industry: "Logistics",
      type: "Volunteer",
      department: "Supply Chain Management",
      posted: "2 days ago",
      skills: ["Logistics", "Inventory Control", "Coordination"],
      description: "Coordinate logistics and supply chain activities.",
      companyLogo: "/images/company-logos/freightfast.png",
      rating: 4.1,
    },
    {
      id: 14,
      title: "Network Engineer",
      company: "TeleConnect",
      location: "Visakhapatnam",
      salary: "₹6-13 LPA",
      experience: "3-6 Years",
      industry: "Telecom",
      type: "Full-time",
      department: "Technical Support",
      posted: "4 days ago",
      skills: ["Networking", "Cisco", "Troubleshooting"],
      description: "Maintain and optimize network infrastructure.",
      companyLogo: "/images/company-logos/teleconnect.png",
      rating: 4.3,
    },
    {
      id: 15,
      title: "Automobile Technician",
      company: "AutoCare",
      location: "Nagpur",
      salary: "₹3-6 LPA",
      experience: "1-3 Years",
      industry: "Automobile",
      type: "Part-time",
      department: "Engineering",
      posted: "3 days ago",
      skills: ["Vehicle Maintenance", "Diagnostics", "Repair"],
      description: "Perform vehicle repairs and maintenance.",
      companyLogo: "/images/company-logos/autocare.png",
      rating: 3.9,
    },
    {
      id: 16,
      title: "FMCG Sales Executive",
      company: "QuickMart",
      location: "Surat",
      salary: "₹4-8 LPA",
      experience: "2-5 Years",
      industry: "FMCG",
      type: "Contract",
      department: "Sales",
      posted: "2 days ago",
      skills: ["Sales", "Negotiation", "Market Analysis"],
      description: "Drive sales for FMCG products in the region.",
      companyLogo: "/images/company-logos/quickmart.png",
      rating: 4.0,
    },
    // Additional Contract Jobs
    {
      id: 17,
      title: "Project Manager",
      company: "TechSolutions",
      location: "Bangalore",
      salary: "₹12-20 LPA",
      experience: "5-8 Years",
      industry: "IT & Software",
      type: "Contract",
      department: "Project Management",
      posted: "1 day ago",
      skills: ["Agile", "Scrum", "JIRA"],
      description: "Lead software development projects on contract basis.",
      companyLogo: "/images/company-logos/techsolutions.png",
      rating: 4.3,
    },
    {
      id: 18,
      title: "UI/UX Designer",
      company: "DesignHub",
      location: "Mumbai",
      salary: "₹8-15 LPA",
      experience: "3-5 Years",
      industry: "Design",
      type: "Contract",
      department: "Design",
      posted: "3 days ago",
      skills: ["Figma", "Adobe XD", "User Research"],
      description: "Contract position for UI/UX design projects.",
      companyLogo: "/images/company-logos/designhub.png",
      rating: 4.1,
    },
    {
      id: 19,
      title: "DevOps Engineer",
      company: "CloudSystems",
      location: "Hyderabad",
      salary: "₹10-18 LPA",
      experience: "3-6 Years",
      industry: "IT & Software",
      type: "Contract",
      department: "DevOps",
      posted: "4 days ago",
      skills: ["AWS", "Docker", "Kubernetes"],
      description: "Contract role for implementing DevOps practices.",
      companyLogo: "/images/company-logos/cloudsystems.png",
      rating: 4.4,
    },
    // Additional Internship Jobs
    {
      id: 20,
      title: "Marketing Intern",
      company: "AdvertiseMe",
      location: "Delhi",
      salary: "₹2-4 LPA",
      experience: "Fresher",
      industry: "Marketing",
      type: "Internship",
      department: "Marketing",
      posted: "1 day ago",
      skills: ["Social Media", "Content Creation", "Analytics"],
      description: "6-month internship in digital marketing.",
      companyLogo: "/images/company-logos/advertiseme.png",
      rating: 3.9,
    },
    {
      id: 21,
      title: "Software Developer Intern",
      company: "CodeCraft",
      location: "Pune",
      salary: "₹3-5 LPA",
      experience: "Fresher",
      industry: "IT & Software",
      type: "Internship",
      department: "Software Development",
      posted: "2 days ago",
      skills: ["JavaScript", "Python", "Git"],
      description: "Internship for aspiring software developers.",
      companyLogo: "/images/company-logos/codecraft.png",
      rating: 4.2,
    },
    {
      id: 22,
      title: "HR Intern",
      company: "TalentFirst",
      location: "Chennai",
      salary: "₹2-3 LPA",
      experience: "Fresher",
      industry: "HR",
      type: "Internship",
      department: "HR",
      posted: "5 days ago",
      skills: ["Recruitment", "Onboarding", "Employee Engagement"],
      description: "Learn HR processes in a corporate environment.",
      companyLogo: "/images/company-logos/talentfirst.png",
      rating: 4.0,
    },
    // Additional Temporary Jobs
    {
      id: 23,
      title: "Event Coordinator",
      company: "EventMasters",
      location: "Mumbai",
      salary: "₹5-8 LPA",
      experience: "2-4 Years",
      industry: "Events",
      type: "Temporary",
      department: "Operations",
      posted: "3 days ago",
      skills: ["Event Planning", "Vendor Management", "Logistics"],
      description: "Temporary position for festival season events.",
      companyLogo: "/images/company-logos/eventmasters.png",
      rating: 3.8,
    },
    {
      id: 24,
      title: "Seasonal Sales Associate",
      company: "RetailPlus",
      location: "Bangalore",
      salary: "₹3-5 LPA",
      experience: "0-1 Years",
      industry: "Retail",
      type: "Temporary",
      department: "Sales",
      posted: "1 day ago",
      skills: ["Customer Service", "Cash Handling", "Product Knowledge"],
      description: "Temporary position for holiday season sales.",
      companyLogo: "/images/company-logos/retailplus.png",
      rating: 3.7,
    },
    {
      id: 25,
      title: "Tax Consultant",
      company: "FinancePro",
      location: "Delhi",
      salary: "₹6-10 LPA",
      experience: "2-5 Years",
      industry: "Finance",
      type: "Temporary",
      department: "Finance",
      posted: "4 days ago",
      skills: ["Taxation", "GST", "Compliance"],
      description: "Temporary role for tax season support.",
      companyLogo: "/images/company-logos/financepro.png",
      rating: 4.1,
    },
    // Additional Remote Jobs
    {
      id: 26,
      title: "Frontend Developer",
      company: "WebWorks",
      location: "Remote",
      salary: "₹8-16 LPA",
      experience: "2-5 Years",
      industry: "IT & Software",
      type: "Remote",
      department: "Software Development",
      posted: "2 days ago",
      skills: ["React", "TypeScript", "CSS"],
      description: "Fully remote frontend development position.",
      companyLogo: "/images/company-logos/webworks.png",
      rating: 4.3,
    },
    {
      id: 27,
      title: "Content Strategist",
      company: "DigitalWords",
      location: "Remote",
      salary: "₹6-12 LPA",
      experience: "3-6 Years",
      industry: "Marketing",
      type: "Remote",
      department: "Content",
      posted: "5 days ago",
      skills: ["Content Strategy", "SEO", "Editorial Planning"],
      description: "Remote content strategy role with flexible hours.",
      companyLogo: "/images/company-logos/digitalwords.png",
      rating: 4.0,
    },
    {
      id: 28,
      title: "Customer Success Manager",
      company: "SaaSolutions",
      location: "Remote",
      salary: "₹7-14 LPA",
      experience: "3-5 Years",
      industry: "Customer Support",
      type: "Remote",
      department: "Customer Success",
      posted: "3 days ago",
      skills: ["Account Management", "CRM", "Onboarding"],
      description: "Manage client relationships remotely.",
      companyLogo: "/images/company-logos/saasolutions.png",
      rating: 4.2,
    },
    // Additional Freelance Jobs
    {
      id: 29,
      title: "Graphic Designer",
      company: "CreativeMinds",
      location: "Remote",
      salary: "₹5-10 LPA",
      experience: "2-5 Years",
      industry: "Design",
      type: "Freelance",
      department: "Design",
      posted: "3 days ago",
      skills: ["Photoshop", "Illustrator", "Branding"],
      description: "Freelance graphic design projects for various clients.",
      companyLogo: "/images/company-logos/creativeminds.png",
      rating: 4.1,
    },
    {
      id: 30,
      title: "Social Media Manager",
      company: "BuzzSocial",
      location: "Remote",
      salary: "₹4-8 LPA",
      experience: "1-3 Years",
      industry: "Marketing",
      type: "Freelance",
      department: "Marketing",
      posted: "2 days ago",
      skills: ["Instagram", "Facebook", "Content Creation"],
      description: "Manage social media accounts for multiple brands.",
      companyLogo: "/images/company-logos/buzzsocial.png",
      rating: 3.9,
    },
    {
      id: 31,
      title: "Copywriter",
      company: "WordSmiths",
      location: "Remote",
      salary: "₹6-12 LPA",
      experience: "3-5 Years",
      industry: "Media",
      type: "Freelance",
      department: "Content",
      posted: "4 days ago",
      skills: ["Copywriting", "Advertising", "Brand Voice"],
      description: "Freelance copywriting for ads and marketing materials.",
      companyLogo: "/images/company-logos/wordsmiths.png",
      rating: 4.2,
    },
    {
      id: 32,
      title: "Photographer",
      company: "SnapShots",
      location: "Delhi",
      salary: "₹3-6 LPA",
      experience: "1-3 Years",
      industry: "Media",
      type: "Freelance",
      department: "Photography",
      posted: "1 day ago",
      skills: ["Portrait", "Product", "Editing"],
      description: "Freelance photography assignments for events and products.",
      companyLogo: "/images/company-logos/snapshots.png",
      rating: 4.0,
    },
    // Additional Volunteer Jobs
    {
      id: 33,
      title: "Community Coordinator",
      company: "HelpingHands",
      location: "Bangalore",
      salary: "Volunteer",
      experience: "Any",
      industry: "Non-Profit",
      type: "Volunteer",
      department: "Community",
      posted: "2 days ago",
      skills: ["Communication", "Organization", "Event Planning"],
      description: "Coordinate community outreach programs and events.",
      companyLogo: "/images/company-logos/helpinghands.png",
      rating: 4.5,
    },
    {
      id: 34,
      title: "Animal Shelter Assistant",
      company: "PawsCare",
      location: "Mumbai",
      salary: "Volunteer",
      experience: "Any",
      industry: "Animal Welfare",
      type: "Volunteer",
      department: "Care",
      posted: "5 days ago",
      skills: ["Animal Care", "Compassion", "Teamwork"],
      description: "Help care for animals at our shelter facility.",
      companyLogo: "/images/company-logos/pawscare.png",
      rating: 4.7,
    },
    {
      id: 35,
      title: "Education Volunteer",
      company: "TeachForAll",
      location: "Hyderabad",
      salary: "Volunteer",
      experience: "Any",
      industry: "Education",
      type: "Volunteer",
      department: "Teaching",
      posted: "3 days ago",
      skills: ["Teaching", "Patience", "Subject Knowledge"],
      description: "Teach underprivileged children basic subjects.",
      companyLogo: "/images/company-logos/teachforall.png",
      rating: 4.6,
    },
    {
      id: 36,
      title: "Environmental Cleanup Volunteer",
      company: "GreenEarth",
      location: "Chennai",
      salary: "Volunteer",
      experience: "Any",
      industry: "Environment",
      type: "Volunteer",
      department: "Conservation",
      posted: "1 day ago",
      skills: ["Environmental Awareness", "Physical Work", "Teamwork"],
      description: "Participate in beach and park cleanup initiatives.",
      companyLogo: "/images/company-logos/greenearth.png",
      rating: 4.4,
    },
    {
      id: 37,
      title: "Tech Mentor for Students",
      company: "CodeForGood",
      location: "Remote",
      salary: "Volunteer",
      experience: "1-3 Years",
      industry: "Education",
      type: "Volunteer",
      department: "Mentoring",
      posted: "4 days ago",
      skills: ["Programming", "Teaching", "Patience"],
      description: "Mentor students learning to code in online sessions.",
      companyLogo: "/images/company-logos/codeforgood.png",
      rating: 4.3,
    },
    {
      id: 38,
      title: "Hospital Volunteer",
      company: "HealthFirst",
      location: "Delhi",
      salary: "Volunteer",
      experience: "Any",
      industry: "Healthcare",
      type: "Volunteer",
      department: "Support",
      posted: "2 days ago",
      skills: ["Compassion", "Communication", "Empathy"],
      description: "Assist patients and staff in hospital operations.",
      companyLogo: "/images/company-logos/healthfirst.png",
      rating: 4.5,
    },
  ];
  
  export const categories = [
    "IT & Software",
    "HR & Recruitment",
    "Sales & Marketing",
    "Finance & Accounting",
    "Operations",
    "Banking Services",
    "Healthcare",
    "Education",
    "Customer Support",
    "Retail",
    "Real Estate",
    "Engineering",
    "Construction",
    "Legal",
    "Media",
    "Hospitality",
    "Logistics",
    "Telecom",
    "Automobile",
    "FMCG",
  ];
  
  export const jobTypes = [
    "Full-time",
    "Part-time",
    "Contract",
    "Internship",
    "Temporary",
    "Remote",
    "Freelance",
    "Volunteer",
  ];
  
  export const industries = [
    "IT & Software",
    "Healthcare",
    "Finance & Banking",
    "Manufacturing",
    "Education",
    "Retail",
    "Automotive",
    "Telecom",
    "Pharmaceuticals",
    "Construction",
    "Media & Entertainment",
    "Energy & Utilities",
    "Aerospace",
    "Hospitality & Tourism",
    "Agriculture",
    "Transportation & Logistics",
    "Cybersecurity",
    "Legal Services",
  ];
  
  export const departments = [
    "Software Development",
    "HR",
    "Finance and Accounts",
    "Marketing",
    "Operations",
    "Customer Support",
    "Sales",
    "Research & Development",
    "Business Development",
    "Legal",
    "Public Relations",
    "Administration",
    "Product Management",
    "Quality Assurance",
    "Design",
    "Technical Support",
    "Supply Chain Management",
    "Consulting",
  ];
  
  export const locations = [
    "Hyderabad",
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Chennai",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Indore",
    "Chandigarh",
    "Coimbatore",
    "Visakhapatnam",
    "Nagpur",
    "Surat",
    "Bhubaneswar",
    "Noida",
    "Gurgaon",
    "Thiruvananthapuram",
    "Remote"
  ];
  
  export const experienceLevels = [
    "Fresher",
    "0-1 Years",
    "1-3 Years",
    "3-5 Years",
    "5-8 Years",
    "8+ Years",
  ];
  
  export const ads = [
    {
      id: 1,
      title: "Hiring Fast?",
      description:
        "Get your jobs seen by 1M+ candidates in 24 hours with our premium listings.",
      cta: "Boost Your Post",
      link: "#",
      bgColor: "bg-blue-200",
      icon: "🚀",
    },
    {
      id: 2,
      title: "Reach Top Talent",
      description:
        "Advertise your openings to skilled professionals across industries.",
      cta: "Post a Job",
      link: "#",
      bgColor: "bg-green-200",
      icon: "🎯",
    },
    {
      id: 3,
      title: "Grow Your Team",
      description:
        "Find the perfect candidates with our advanced matching algorithms.",
      cta: "Explore Plans",
      link: "#",
      bgColor: "bg-purple-200",
      icon: "📈",
    },
    {
      id: 4,
      title: "Need Interns?",
      description:
        "Connect with fresh talent from top universities for internships.",
      cta: "Hire Interns",
      link: "#",
      bgColor: "bg-yellow-200",
      icon: "💡",
    },
    {
      id: 5,
      title: "Premium Listings",
      description: "Stand out with featured job posts and priority visibility.",
      cta: "Upgrade Now",
      link: "#",
      bgColor: "bg-pink-200",
      icon: "🌟",
    },
    {
      id: 6,
      title: "Partner with Us",
      description: "Collaborate to access exclusive hiring tools and insights.",
      cta: "Contact Us",
      link: "#",
      bgColor: "bg-teal-200",
      icon: "🤝",
    },
    {
      id: 7,
      title: "Search Smarter",
      description:
        "Use our AI-driven tools to find candidates that match your needs.",
      cta: "Try Now",
      link: "#",
      bgColor: "bg-orange-200",
      icon: "🔍",
    },
    {
      id: 8,
      title: "Promote Your Brand",
      description: "Showcase your company culture to attract top talent.",
      cta: "Learn More",
      link: "#",
      bgColor: "bg-indigo-200",
      icon: "📣",
    },
  ];
