//src/app/companies/components/companyData.js
// This file is deprecated - companies are now fetched from the database API
// Only keeping the static data for reference purposes

export const companies = [
  // MNC Companies
  {
    id: 1,
    name: "ABC Tech",
    location: "Hyderabad",
    jobs: 12,
    industry: "IT & Software",
    type: "MNC",
    department: "Software Development",
    salary: "₹4-10 LPA",
    experience: "2-6 Years",
    rating: 4.2,
    logo: "/images/company-logos/abc-tech.png",
    description: "ABC Tech is a leading global technology services company.",
  },
  {
    id: 2,
    name: "Infowave Solutions",
    location: "Bangalore",
    jobs: 18,
    industry: "IT Services",
    type: "MNC",
    department: "Enterprise Solutions",
    salary: "₹5-12 LPA",
    experience: "3-7 Years",
    rating: 4.4,
    logo: "/images/company-logos/infowave.png",
    description:
      "Infowave Solutions offers cutting-edge enterprise digital transformation services.",
  },
  {
    id: 3,
    name: "BlueStar Systems",
    location: "Pune",
    jobs: 10,
    industry: "Telecommunications",
    type: "MNC",
    department: "Networking",
    salary: "₹6-14 LPA",
    experience: "2-5 Years",
    rating: 4.1,
    logo: "/images/company-logos/bluestar.png",
    description:
      "BlueStar Systems is a leader in advanced networking and telecommunication solutions.",
  },

  // Startup Companies
  {
    id: 4,
    name: "QuickHire",
    location: "Chennai",
    jobs: 7,
    industry: "Recruitment Tech",
    type: "Startup",
    department: "Technology",
    salary: "₹4-8 LPA",
    experience: "1-3 Years",
    rating: 4.6,
    logo: "/images/company-logos/quickhire.png",
    description:
      "QuickHire is a fast-growing recruitment platform simplifying hiring for startups.",
  },
  {
    id: 5,
    name: "GreenByte",
    location: "Mumbai",
    jobs: 5,
    industry: "Clean Tech",
    type: "Startup",
    department: "Research & Development",
    salary: "₹5-9 LPA",
    experience: "0-2 Years",
    rating: 4.5,
    logo: "/images/company-logos/greenbyte.png",
    description:
      "GreenByte is driving innovation in renewable energy and sustainable technologies.",
  },
  {
    id: 6,
    name: "FinNest",
    location: "Gurgaon",
    jobs: 9,
    industry: "FinTech",
    type: "Startup",
    department: "Software Engineering",
    salary: "₹6-11 LPA",
    experience: "1-4 Years",
    rating: 4.3,
    logo: "/images/company-logos/finnest.png",
    description:
      "FinNest is revolutionizing personal finance management through smart apps.",
  },

  // Foreign MNC Companies
  {
    id: 7,
    name: "Globex Corporation",
    location: "New York, USA",
    jobs: 20,
    industry: "Enterprise IT",
    type: "Foreign MNC",
    department: "Cloud Services",
    salary: "$80k-$130k",
    experience: "4-8 Years",
    rating: 4.7,
    logo: "/images/company-logos/globex.png",
    description:
      "Globex Corporation is a Fortune 500 IT and cloud services company.",
  },
  {
    id: 8,
    name: "Initech",
    location: "London, UK",
    jobs: 15,
    industry: "Financial Services",
    type: "Foreign MNC",
    department: "Financial Tech",
    salary: "£50k-£90k",
    experience: "3-6 Years",
    rating: 4.5,
    logo: "/images/company-logos/initech.png",
    description:
      "Initech provides financial technology solutions to clients worldwide.",
  },
  {
    id: 9,
    name: "Cyberdyne Systems",
    location: "Tokyo, Japan",
    jobs: 25,
    industry: "Robotics & AI",
    type: "Foreign MNC",
    department: "Artificial Intelligence",
    salary: "¥6M-¥12M",
    experience: "5-10 Years",
    rating: 4.8,
    logo: "/images/company-logos/cyberdyne.png",
    description:
      "Cyberdyne Systems is pioneering the future of robotics and human augmentation.",
  },

  // Manufacturing MNC Companies
  {
    id: 10,
    name: "Larsen & Toubro",
    location: "Mumbai",
    jobs: 14,
    industry: "Construction & Manufacturing",
    type: "Manufacturing MNC",
    department: "Project Management",
    salary: "₹5-13 LPA",
    experience: "2-6 Years",
    rating: 4.2,
    logo: "/images/company-logos/lt.png",
    description:
      "L&T is a major technology, engineering, construction, and manufacturing company.",
  },
  {
    id: 11,
    name: "Tata Steel",
    location: "Jamshedpur",
    jobs: 12,
    industry: "Steel Manufacturing",
    type: "Manufacturing MNC",
    department: "Production",
    salary: "₹4-9 LPA",
    experience: "1-5 Years",
    rating: 4.3,
    logo: "/images/company-logos/tata-steel.png",
    description:
      "Tata Steel is one of the world's largest steel manufacturers with global presence.",
  },
  {
    id: 12,
    name: "Siemens",
    location: "Gurgaon",
    jobs: 18,
    industry: "Electronics & Engineering",
    type: "Manufacturing MNC",
    department: "Automation",
    salary: "₹6-15 LPA",
    experience: "3-7 Years",
    rating: 4.5,
    logo: "/images/company-logos/siemens.png",
    description:
      "Siemens AG is a global powerhouse in electrification, automation, and digitization.",
  },

  // Healthcare MNC Companies
  {
    id: 13,
    name: "Pfizer",
    location: "Mumbai",
    jobs: 10,
    industry: "Pharmaceuticals",
    type: "Healthcare MNC",
    department: "Medical Research",
    salary: "₹7-16 LPA",
    experience: "2-6 Years",
    rating: 4.4,
    logo: "/images/company-logos/pfizer.png",
    description:
      "Pfizer is a leading pharmaceutical company innovating vaccines and medicines.",
  },
  {
    id: 14,
    name: "Johnson & Johnson",
    location: "Delhi",
    jobs: 8,
    industry: "Healthcare",
    type: "Healthcare MNC",
    department: "Healthcare Sales",
    salary: "₹6-14 LPA",
    experience: "2-5 Years",
    rating: 4.5,
    logo: "/images/company-logos/jnj.png",
    description:
      "Johnson & Johnson is a global leader in healthcare products and medical devices.",
  },
  {
    id: 15,
    name: "Medtronic",
    location: "Bangalore",
    jobs: 9,
    industry: "Medical Devices",
    type: "Healthcare MNC",
    department: "Medical Engineering",
    salary: "₹8-18 LPA",
    experience: "3-7 Years",
    rating: 4.6,
    logo: "/images/company-logos/medtronic.png",
    description:
      "Medtronic is advancing healthcare through medical technologies and therapies.",
  },

  // NGO Companies
  {
    id: 16,
    name: "Helping Hands",
    location: "Bangalore",
    jobs: 5,
    industry: "Non-Profit",
    type: "NGO",
    department: "Community",
    salary: "Volunteer",
    experience: "Any",
    rating: 4.5,
    logo: "/images/company-logos/helpinghands.png",
    description:
      "Helping Hands is dedicated to community development and social welfare.",
  },
  {
    id: 17,
    name: "Green Earth",
    location: "Delhi",
    jobs: 4,
    industry: "Environment",
    type: "NGO",
    department: "Conservation",
    salary: "Volunteer",
    experience: "Any",
    rating: 4.7,
    logo: "/images/company-logos/greenearth.png",
    description:
      "Green Earth focuses on environmental conservation and sustainability.",
  },
  {
    id: 18,
    name: "Teach For India",
    location: "Mumbai",
    jobs: 6,
    industry: "Education",
    type: "NGO",
    department: "Teaching",
    salary: "Volunteer",
    experience: "Any",
    rating: 4.8,
    logo: "/images/company-logos/teachforindia.png",
    description:
      "Teach For India is working to eliminate educational inequity by placing outstanding college graduates in low-income schools.",
  },
  {
    id: 19,
    name: "Goonj",
    location: "Delhi",
    jobs: 4,
    industry: "Community Development",
    type: "NGO",
    department: "Operations",
    salary: "Volunteer",
    experience: "Any",
    rating: 4.7,
    logo: "/images/company-logos/goonj.png",
    description:
      "Goonj is a social enterprise creating a parallel economy with the underutilized urban material as a tool.",
  },
];

export const companyTypes = [
  "MNC",
  "Foreign MNC",
  "Startup",
  "Manufacturing MNC",
  "Healthcare MNC",
  "NGO",
  "MSME",
  "Public Sector",
  "Small Industry",
  "Partnership",
  "Cooperative",
  "Nonprofit",
  "Sole Proprietorship",
  "Government Organization",
  "Private Limited Company",
  "Public Limited Company",
  "Educational Institution",
  "Research Organization",
  "Healthcare Institution",
];

export const industries = [
  "IT & Software",
  "Healthcare",
  "Finance & Banking",
  "Manufacturing",
  "Education",
  "Retail",
  "Automotive",
  "Telecom",
  "Pharmaceuticals",
  "Construction",
  "Media & Entertainment",
  "Energy & Utilities",
  "Aerospace",
  "Hospitality & Tourism",
  "Agriculture",
  "Transportation & Logistics",
  "Cybersecurity",
  "Legal Services",
  "Non-Profit",
  "Environment",
];

export const departments = [
  "Software Development",
  "HR",
  "Finance and Accounts",
  "Marketing",
  "Operations",
  "Customer Support",
  "Sales",
  "Research & Development",
  "Business Development",
  "Legal",
  "Public Relations",
  "Administration",
  "Product Management",
  "Quality Assurance",
  "Design",
  "Technical Support",
  "Supply Chain Management",
  "Consulting",
  "Community",
  "Conservation",
];

export const locations = [
  "Hyderabad",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Indore",
  "Chandigarh",
  "Coimbatore",
  "Visakhapatnam",
  "Nagpur",
  "Surat",
  "Bhubaneswar",
  "Noida",
  "Gurgaon",
  "Thiruvananthapuram",
  "New York, USA",
  "London, UK",
  "Tokyo, Japan",
  "Jamshedpur",
];

export const ads = [
  {
    id: 1,
    title: "🚀 Hiring Fast?",
    description:
      "Get your jobs seen by 1M+ candidates in 24 hours with our premium listings.",
    cta: "Boost Your Post",
    link: "#",
    bgColor: "bg-blue-200",
    icon: "💼",
  },
  {
    id: 2,
    title: "🏢 Join Top Startups!",
    description:
      "Explore 5,000+ startup jobs in tech, marketing, and design. Fresh openings every day.",
    cta: "Browse Jobs",
    link: "#",
    bgColor: "bg-yellow-200",
    icon: "🚀",
  },
  {
    id: 3,
    title: "🌍 Work Remotely",
    description:
      "Discover remote opportunities from global tech giants and emerging startups.",
    cta: "Find Remote Jobs",
    link: "#",
    bgColor: "bg-green-200",
    icon: "🌐",
  },
  {
    id: 4,
    title: "💰 Salary Benchmarking",
    description:
      "Get personalized salary insights and know what you deserve before you negotiate.",
    cta: "Check Salaries",
    link: "#",
    bgColor: "bg-purple-200",
    icon: "📈",
  },
  {
    id: 5,
    title: "🎯 Hire Top Talent",
    description:
      "Post a job and reach vetted professionals actively looking for new roles.",
    cta: "Post a Job",
    link: "#",
    bgColor: "bg-pink-200",
    icon: "🎯",
  },
  {
    id: 6,
    title: "🧑‍💻 Tech Jobs Hotlist",
    description:
      "Latest openings for developers, designers, and PMs at Amazon, Google, and top startups.",
    cta: "View Listings",
    link: "#",
    bgColor: "bg-indigo-200",
    icon: "🛠️",
  },
  {
    id: 7,
    title: "🏆 Top Companies Hiring",
    description:
      "Apply to jobs at Fortune 500 companies and fast-growing startups, all in one place.",
    cta: "See Companies",
    link: "#",
    bgColor: "bg-orange-200",
    icon: "🏢",
  },
  {
    id: 8,
    title: "🎓 Freshers Welcome!",
    description:
      "Thousands of entry-level roles now open for 2024 graduates across India and abroad.",
    cta: "Explore Fresher Jobs",
    link: "#",
    bgColor: "bg-teal-200",
    icon: "🎓",
  },
  {
    id: 9,
    title: "🎯 Startup Hiring Frenzy",
    description:
      "Join fast-growing startups and get early growth opportunities.",
    cta: "View Startup Jobs",
    link: "#",
    bgColor: "bg-pink-200",
    icon: "🚀",
  },
  {
    id: 10,
    title: "💼 Executive Openings",
    description: "C-level roles open in Fortune 500 companies. Apply today!",
    cta: "Apply Now",
    link: "#",
    bgColor: "bg-indigo-200",
    icon: "👔",
  },
  {
    id: 11,
    title: "🧑‍💻 Internships for Freshers",
    description:
      "Kickstart your career with paid internships across industries.",
    cta: "Find Internships",
    link: "#",
    bgColor: "bg-teal-200",
    icon: "🎓",
  },
  {
    id: 12,
    title: "🚀 Fast-Track Your Hiring",
    description:
      "Post a job today and start receiving applications within hours!",
    cta: "Post a Job",
    link: "#",
    bgColor: "bg-lime-200",
    icon: "📢",
  },
  {
    id: 13,
    title: "📝 Instant Resume Builder",
    description:
      "Build a professional resume in minutes with our AI-powered tool.",
    cta: "Create Resume",
    link: "#",
    bgColor: "bg-fuchsia-200",
    icon: "🖋️",
  },
  {
    id: 14,
    title: "📊 Free Skill Assessments",
    description:
      "Take industry-standard skill tests and add badges to your profile.",
    cta: "Take a Test",
    link: "#",
    bgColor: "bg-amber-200",
    icon: "🏅",
  },
  {
    id: 15,
    title: "🌐 Explore Jobs Abroad",
    description: "Dreaming of working overseas? Find jobs in 20+ countries!",
    cta: "Search Jobs",
    link: "#",
    bgColor: "bg-sky-200",
    icon: "✈️",
  },
  {
    id: 16,
    title: "📚 Learning Courses for Free",
    description: "Enroll in free tech, business, and design courses today.",
    cta: "Start Learning",
    link: "#",
    bgColor: "bg-emerald-200",
    icon: "📚",
  },
  {
    id: 17,
    title: "🧑‍🎓 Scholarships Available!",
    description:
      "Apply for career-boosting scholarships in tech and management.",
    cta: "Apply Now",
    link: "#",
    bgColor: "bg-violet-200",
    icon: "🎓",
  },
  {
    id: 18,
    title: "🛠️ Top Developer Roles",
    description:
      "Get hired by leading tech companies looking for full-stack developers and engineers.",
    cta: "Apply for Tech Jobs",
    link: "#",
    bgColor: "bg-blue-200",
    icon: "🖥️",
  },
  {
    id: 19,
    title: "📈 MBA Graduates in Demand",
    description:
      "Find top management and consultant roles for MBA graduates across India and abroad.",
    cta: "View MBA Jobs",
    link: "#",
    bgColor: "bg-rose-200",
    icon: "📊",
  },
  {
    id: 20,
    title: "🏡 Hybrid Jobs Near You",
    description:
      "Flexible hybrid jobs available across major Indian cities. Part remote, part onsite!",
    cta: "Explore Hybrid Jobs",
    link: "#",
    bgColor: "bg-green-200",
    icon: "🏡",
  },
  {
    id: 21,
    title: "🏅 Top Employer Awards",
    description: "Apply to companies recognized as Top Workplaces of 2025!",
    cta: "View Companies",
    link: "#",
    bgColor: "bg-rose-200",
    icon: "🏆",
  },
  {
    id: 22,
    title: "👩‍💻 Women in Tech",
    description:
      "Exclusive hiring drives for women in technology across top firms.",
    cta: "See Opportunities",
    link: "#",
    bgColor: "bg-pink-200",
    icon: "👩‍💻",
  },
  {
    id: 23,
    title: "🏠 Work-From-Home Jobs",
    description: "Find 100% remote roles in marketing, software, and more.",
    cta: "Apply Now",
    link: "#",
    bgColor: "bg-gray-200",
    icon: "🏡",
  },
  {
    id: 24,
    title: "🛠 Learn In-Demand Skills",
    description: "Master Python, React, AI, and Cloud Computing for free!",
    cta: "Start Learning",
    link: "#",
    bgColor: "bg-yellow-200",
    icon: "🧠",
  },
];
