# Generated by Django 5.2.3 on 2025-10-20 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("profile_update", "Profile Updated"),
                            ("job_post", "Job Posted"),
                            ("job_apply", "Job Application"),
                            ("message_sent", "Message Sent"),
                            ("search", "Search Performed"),
                            ("view", "Page/Item Viewed"),
                            ("upload", "File Uploaded"),
                            ("download", "File Downloaded"),
                            ("settings_change", "Settings Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(default="127.0.0.1")),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserDataSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50)),
                ("data_content", models.JSONField(default=dict)),
                ("device_id", models.CharField(blank=True, max_length=100)),
                ("last_sync", models.DateTimeField(auto_now=True)),
                ("sync_version", models.IntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-last_sync"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("hi", "Hindi"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("dashboard_layout", models.JSONField(blank=True, default=dict)),
                (
                    "default_page",
                    models.CharField(default="/dashboard", max_length=100),
                ),
                ("items_per_page", models.IntegerField(default=10)),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="instant",
                        max_length=20,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("connections", "Connections Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("allow_search", models.BooleanField(default=True)),
                ("show_activity_status", models.BooleanField(default=True)),
                ("custom_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={"ordering": ["-last_activity"]},
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="profile_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="device_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="usersession",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("web", "Web Browser"),
                    ("mobile", "Mobile App"),
                    ("tablet", "Tablet"),
                    ("desktop", "Desktop App"),
                ],
                default="web",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="ip_address",
            field=models.GenericIPAddressField(default="127.0.0.1"),
        ),
        migrations.AddField(
            model_name="usersession",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="location_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="usersession",
            name="login_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usersession",
            name="logout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="session_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="usersession",
            name="session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["user", "provider"], name="authenticat_user_id_36c1fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["social_id"], name="authenticat_social__46889e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="authenticat_user_id_f427c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_id"], name="authenticat_session_b41e7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="authenticat_last_ac_04a1e9_idx"
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.usersession",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdatasync",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_syncs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "activity_type"], name="authenticat_user_id_b8ae42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["timestamp"], name="authenticat_timesta_f33446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdatasync",
            index=models.Index(
                fields=["user", "data_type", "is_latest"],
                name="authenticat_user_id_54b114_idx",
            ),
        ),
    ]
