# Generated by Django 5.2.3 on 2025-10-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_useractivity_userdatasync_userpreferences_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Verification"),
                            ("phone", "Phone Verification"),
                            ("password_reset", "Password Reset"),
                            ("login_2fa", "Two-Factor Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_otp_session",
                "indexes": [
                    models.Index(
                        fields=["identifier", "verification_type"],
                        name="auth_otp_se_identif_c4f99a_idx",
                    ),
                    models.Index(
                        fields=["otp_code"], name="auth_otp_se_otp_cod_39c94e_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="auth_otp_se_expires_35bf59_idx"
                    ),
                ],
            },
        ),
    ]
