# Generated by Django 5.2.3 on 2025-10-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_otpsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("employer", "Employer"),
                            ("partner", "Training Partner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Registration"),
                            ("otp_verified", "OTP Verified"),
                            ("profile_setup", "Profile Setup"),
                            ("completed", "Registration Completed"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("user_data", models.JSONField(blank=True, default=dict)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_registration_cache",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "email"],
                        name="auth_regist_session_67f98e_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="auth_regist_expires_c1a671_idx"
                    ),
                    models.Index(
                        fields=["current_step"], name="auth_regist_current_16d01e_idx"
                    ),
                ],
            },
        ),
    ]
