# Generated by Django 5.2.3 on 2025-11-01 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_registrationcache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="registrationcache",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="session",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userdatasync",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="socialaccount",
            name="authenticat_user_id_36c1fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="socialaccount",
            name="authenticat_social__46889e_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersession",
            name="authenticat_user_id_f427c8_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersession",
            name="authenticat_session_b41e7c_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersession",
            name="authenticat_last_ac_04a1e9_idx",
        ),
        migrations.RemoveField(
            model_name="socialaccount",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="socialaccount",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="socialaccount",
            name="profile_data",
        ),
        migrations.RemoveField(
            model_name="socialaccount",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="socialaccount",
            name="token_expires_at",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="device_info",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="device_type",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="last_activity",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="location_data",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="login_time",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="logout_time",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="session_data",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user_agent",
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="refresh_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="OTPSession",
        ),
        migrations.DeleteModel(
            name="RegistrationCache",
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
        migrations.DeleteModel(
            name="UserDataSync",
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
