# Generated by Django 5.2.3 on 2025-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_otpsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpsession",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                ],
                max_length=20,
            ),
        ),
    ]
