# Generated by Django 5.2.3 on 2025-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="current_designation",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="github_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="image_field_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="resume_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="current_position",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="github_profile",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="linkedin_profile",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="portfolio_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="profile_picture",
            field=models.URLField(blank=True, default=""),
        ),
    ]
