# Generated by Django 5.2.4 on 2025-10-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0002_employeeprofile_current_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.URLField(blank=True)),
                ('template_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='color_scheme',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='custom_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_family',
            field=models.CharField(default='Arial', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='page_margins',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='personal_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('professional', 'Professional'), ('minimal', 'Minimal'), ('executive', 'Executive')], default='modern', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='ResumeSharingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('password_protected', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_link', to='employee_dashboard.resume')),
            ],
        ),
    ]
