# Generated by Django 5.2.4 on 2025-10-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0003_resumetemplate_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('key_skills', models.TextField(blank=True, default='')),
                ('present_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period', models.CharField(blank=True, default='', max_length=50)),
                ('preferred_location', models.CharField(blank=True, default='', max_length=255)),
                ('actively_looking', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, default='', max_length=255)),
                ('achievements', models.TextField(blank=True, default='')),
                ('availability_schedule', models.CharField(blank=True, default='', max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('contact_call', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_sms', models.CharField(blank=True, default='', max_length=20)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_searchable', models.BooleanField(default=True)),
                ('match_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to='employee_dashboard.employeeprofile')),
            ],
            options={
                'db_table': 'employee_dashboard_candidatesearchprofile',
            },
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies_used', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='employee_dashboard.candidatesearchprofile')),
            ],
            options={
                'db_table': 'employee_dashboard_candidateproject',
            },
        ),
        migrations.CreateModel(
            name='CandidateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_details', to='employee_dashboard.candidatesearchprofile')),
            ],
            options={
                'db_table': 'employee_dashboard_candidateachievement',
            },
        ),
    ]
