# Generated by Django 5.2.3 on 2025-10-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0004_candidatesearchprofile_candidateproject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("connections", "Connections Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("show_profile_picture", models.BooleanField(default=True)),
                ("show_contact_info", models.BooleanField(default=True)),
                ("show_experience", models.BooleanField(default=True)),
                ("show_education", models.BooleanField(default=True)),
                ("show_skills", models.BooleanField(default=True)),
                ("show_resume", models.BooleanField(default=True)),
                ("allow_profile_indexing", models.BooleanField(default=True)),
                ("profile_completion_reminder", models.BooleanField(default=True)),
                (
                    "job_alert_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("preferred_job_types", models.JSONField(default=list)),
                ("preferred_work_modes", models.JSONField(default=list)),
                ("preferred_industries", models.JSONField(default=list)),
                ("preferred_company_sizes", models.JSONField(default=list)),
                (
                    "salary_range_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_range_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("preferred_locations", models.JSONField(default=list)),
                ("exclude_companies", models.JSONField(default=list)),
                ("auto_apply_enabled", models.BooleanField(default=False)),
                ("auto_apply_criteria", models.JSONField(default=dict)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("job_recommendations", models.BooleanField(default=True)),
                ("application_updates", models.BooleanField(default=True)),
                ("interview_reminders", models.BooleanField(default=True)),
                ("profile_views", models.BooleanField(default=True)),
                ("new_messages", models.BooleanField(default=True)),
                ("skills_suggestions", models.BooleanField(default=True)),
                ("course_recommendations", models.BooleanField(default=True)),
                ("newsletter_subscription", models.BooleanField(default=False)),
                ("marketing_emails", models.BooleanField(default=False)),
                ("notification_sound", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("allow_recruiter_contact", models.BooleanField(default=True)),
                ("allow_employer_search", models.BooleanField(default=True)),
                ("show_salary_expectations", models.BooleanField(default=False)),
                ("show_current_employer", models.BooleanField(default=True)),
                ("anonymous_profile_views", models.BooleanField(default=False)),
                (
                    "data_retention_period",
                    models.CharField(
                        choices=[
                            ("1year", "1 Year"),
                            ("2years", "2 Years"),
                            ("5years", "5 Years"),
                            ("indefinite", "Indefinite"),
                        ],
                        default="2years",
                        max_length=20,
                    ),
                ),
                ("allow_data_export", models.BooleanField(default=True)),
                ("third_party_sharing", models.BooleanField(default=False)),
                ("analytics_tracking", models.BooleanField(default=True)),
                ("cookie_preferences", models.JSONField(default=dict)),
                ("application_status_updates", models.BooleanField(default=True)),
                ("track_application_views", models.BooleanField(default=True)),
                ("save_application_drafts", models.BooleanField(default=True)),
                ("auto_save_frequency", models.IntegerField(default=30)),
                ("application_reminder_days", models.IntegerField(default=7)),
                ("follow_up_reminders", models.BooleanField(default=True)),
                ("application_analytics", models.BooleanField(default=True)),
                ("export_applications", models.BooleanField(default=True)),
                (
                    "default_resume_template",
                    models.CharField(default="modern", max_length=50),
                ),
                ("auto_save_resume", models.BooleanField(default=True)),
                ("resume_version_history", models.BooleanField(default=True)),
                ("max_resume_versions", models.IntegerField(default=10)),
                ("resume_backup_enabled", models.BooleanField(default=True)),
                ("resume_sharing_enabled", models.BooleanField(default=True)),
                ("resume_analytics", models.BooleanField(default=True)),
                ("watermark_enabled", models.BooleanField(default=False)),
                ("password_protect_resume", models.BooleanField(default=False)),
                ("interview_reminder_time", models.IntegerField(default=60)),
                ("mock_interview_enabled", models.BooleanField(default=True)),
                ("skill_assessment_reminders", models.BooleanField(default=True)),
                (
                    "practice_question_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                ("interview_feedback_sharing", models.BooleanField(default=True)),
                ("assessment_history_retention", models.IntegerField(default=12)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("platform", "Platform Message"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_expectation",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("1hour", "1 Hour"),
                            ("24hours", "24 Hours"),
                            ("3days", "3 Days"),
                        ],
                        default="24hours",
                        max_length=20,
                    ),
                ),
                ("language_preference", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "dashboard_layout",
                    models.CharField(
                        choices=[
                            ("grid", "Grid"),
                            ("list", "List"),
                            ("compact", "Compact"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                ("items_per_page", models.IntegerField(default=20)),
                ("show_quick_stats", models.BooleanField(default=True)),
                ("show_progress_bars", models.BooleanField(default=True)),
                ("show_recommendations", models.BooleanField(default=True)),
                ("show_activity_feed", models.BooleanField(default=True)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("color_scheme", models.CharField(default="blue", max_length=20)),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("login_notifications", models.BooleanField(default=True)),
                ("session_timeout", models.IntegerField(default=1440)),
                ("password_expiry_days", models.IntegerField(default=90)),
                ("security_alerts", models.BooleanField(default=True)),
                ("linkedin_sync", models.BooleanField(default=False)),
                ("github_sync", models.BooleanField(default=False)),
                ("google_calendar_sync", models.BooleanField(default=False)),
                ("external_job_boards", models.JSONField(default=list)),
                ("api_access_enabled", models.BooleanField(default=False)),
                ("webhook_urls", models.JSONField(default=list)),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("auto_renewal", models.BooleanField(default=True)),
                ("billing_notifications", models.BooleanField(default=True)),
                ("usage_alerts", models.BooleanField(default=True)),
                ("feature_access", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="employee_dashboard.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "employee_dashboard_employeesettings",
            },
        ),
    ]
