# Generated by Django 5.2.3 on 2025-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0005_employeesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_backgrounds/"
            ),
        ),
    ]
