# Generated by Django 5.2.3 on 2025-11-11 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0006_employeeprofile_background_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(default="System", max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("job_alert", "Job Alert"),
                            ("application", "Application Update"),
                            ("interview", "Interview"),
                            ("message", "Message"),
                            ("reminder", "Reminder"),
                            ("announcement", "Announcement"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("avatar", models.CharField(default="🔔", max_length=10)),
                ("related_job_id", models.IntegerField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="employee_da_recipie_1251a0_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="employee_da_recipie_7dd7d5_idx",
                    ),
                ],
            },
        ),
    ]
