# Generated by Django 5.2.3 on 2025-11-18 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesearchprofile",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="public_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
