# Generated by Django 5.2.3 on 2025-11-18 05:34

import employee_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0008_candidatesearchprofile_strengths_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="public_identifier",
            field=models.CharField(
                blank=True,
                default=employee_dashboard.models.generate_public_identifier,
                editable=False,
                max_length=40,
                null=True,
            ),
        ),
    ]
