# Generated by Django 5.2.3 on 2025-12-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0010_populate_public_identifier_and_make_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatesearchprofile",
            name="strengths",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="public_id",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="public_identifier",
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="achievements",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="current_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="marital_status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="nationality",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="notice_period",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="professional_mission",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="strengths",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="twitter_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="website_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
