# Generated by Django 5.2.3 on 2025-12-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0011_remove_candidatesearchprofile_strengths_and_more"),
    ]

    operations = [
        # Remove twitter_url field to fix production database schema mismatch
        migrations.RemoveField(
            model_name="employeeprofile",
            name="twitter_url",
        ),
    ]
