# Generated by Django 5.2.3 on 2025-09-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web_development", "Web Development"),
                            ("mobile_development", "Mobile Development"),
                            ("data_science", "Data Science"),
                            ("artificial_intelligence", "Artificial Intelligence"),
                            ("cybersecurity", "Cybersecurity"),
                            ("cloud_computing", "Cloud Computing"),
                            ("digital_marketing", "Digital Marketing"),
                            ("business_analysis", "Business Analysis"),
                            ("project_management", "Project Management"),
                            ("soft_skills", "Soft Skills"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration_weeks", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("capacity", models.IntegerField()),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prerequisites", models.TextField(blank=True)),
                ("learning_outcomes", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True, null=True, upload_to="training_materials/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="training_banners/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_phone", models.CharField(max_length=20)),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("failed", "Failed"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("certificate_issued", models.BooleanField(default=False)),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training_dashboard.trainingprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("placement_date", models.DateField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "training_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="training_dashboard.trainingprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("website", models.URLField(blank=True)),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialization", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="training_logos/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "training_dashboard_trainingproviderprofile",
            },
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="training_dashboard.trainingproviderprofile",
            ),
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("duration_months", models.IntegerField()),
                (
                    "stipend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("application_deadline", models.DateField()),
                ("slots_available", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="training_dashboard.trainingproviderprofile",
                    ),
                ),
            ],
        ),
    ]
