# Generated by Django 5.2.3 on 2025-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Brief description about the organization"
            ),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True, help_text="Years of experience in training", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="facebook_url",
            field=models.URLField(blank=True, help_text="Facebook page URL"),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year the organization was founded", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="qualifications",
            field=models.TextField(
                blank=True, help_text="Key qualifications and certifications"
            ),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="team_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of team members", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="twitter_url",
            field=models.URLField(blank=True, help_text="Twitter profile URL"),
        ),
        migrations.AddField(
            model_name="trainingproviderprofile",
            name="youtube_url",
            field=models.URLField(blank=True, help_text="YouTube channel URL"),
        ),
    ]
