# Generated by Django 5.2.4 on 2025-10-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_dashboard', '0002_alter_job_options_remove_job_experience_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidate_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='employer_dashboard.jobapplication')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='employer_dashboard.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='employer_dashboard.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interview_type', models.CharField(choices=[('video', 'Video Interview'), ('phone', 'Phone Interview'), ('inperson', 'In-Person Interview'), ('assessment', 'Assessment')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('duration', models.IntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1 hour 30 minutes'), (120, '2 hours')], default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=50)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('next_round', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='employer_dashboard.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='employer_dashboard.employerprofile')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='employer_dashboard.job')),
                ('interviewers', models.ManyToManyField(related_name='interviews', to='employer_dashboard.interviewer')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='employer_dashboard.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_dashboard.interviewer')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='employer_dashboard.interviewer')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['interview_date', 'interview_time'], name='employer_da_intervi_3329e6_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['employer', 'status'], name='employer_da_employe_1219a2_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate', 'status'], name='employer_da_candida_150e0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewtimeslot',
            unique_together={('interviewer', 'date', 'start_time')},
        ),
    ]
