# Generated by Django 5.2.4 on 2025-10-19 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_dashboard', '0003_candidate_interviewer_interview_interviewnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('is_datacenter', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('isp', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('as_number', models.CharField(blank=True, max_length=50)),
                ('as_name', models.CharField(blank=True, max_length=255)),
                ('threat_score', models.IntegerField(default=0)),
                ('is_malicious', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('api_sources', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_scans', to='employer_dashboard.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_scans', to='employer_dashboard.employerprofile')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_scans', to='employer_dashboard.interview')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('proxy_detected', 'Proxy Detected'), ('vpn_detected', 'VPN Detected'), ('tor_detected', 'Tor Detected'), ('suspicious_location', 'Suspicious Location'), ('multiple_locations', 'Multiple Locations'), ('high_risk_ip', 'High Risk IP'), ('custom_rule', 'Custom Rule Triggered')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='employer_dashboard.proxyscansession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyDetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('ip_range', 'IP Range'), ('asn', 'ASN Block'), ('country', 'Country Block'), ('isp', 'ISP Block'), ('keyword', 'Keyword Block')], max_length=20)),
                ('rule_value', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('block_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_rules', to='employer_dashboard.employerprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('employer', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='proxyscansession',
            index=models.Index(fields=['employer', '-started_at'], name='employer_da_employe_c1125c_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyscansession',
            index=models.Index(fields=['ip_address'], name='employer_da_ip_addr_426e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyscansession',
            index=models.Index(fields=['scan_status'], name='employer_da_scan_st_9d1284_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyscansession',
            index=models.Index(fields=['risk_level'], name='employer_da_risk_le_ccf171_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyalert',
            index=models.Index(fields=['scan_session', '-created_at'], name='employer_da_scan_se_3ebf52_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyalert',
            index=models.Index(fields=['severity'], name='employer_da_severit_b7771a_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyalert',
            index=models.Index(fields=['is_resolved'], name='employer_da_is_reso_cb01d2_idx'),
        ),
    ]
