# Generated by Django 5.2.4 on 2025-10-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_dashboard', '0004_proxyscansession_proxyalert_proxydetectionrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('position_applied', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('interview_date', models.DateField()),
                ('interview_duration', models.DurationField(blank=True, null=True)),
                ('interview_status', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('hold', 'Hold'), ('shortlisted', 'Shortlisted'), ('next_round', 'Next Round')], max_length=20)),
                ('decision_rationale', models.TextField(blank=True)),
                ('skills_assessment', models.TextField()),
                ('behavior_assessment', models.TextField()),
                ('technical_skills', models.TextField()),
                ('overall_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('skills_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('technical_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('culture_fit_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('offered_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('offer_details', models.JSONField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='employer_dashboard.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='employer_dashboard.employerprofile')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='employer_dashboard.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='employer_dashboard.interviewer')),
            ],
            options={
                'db_table': 'employer_interview_feedback',
                'ordering': ['-interview_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('system', 'System Notification')], max_length=20)),
                ('message', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reminders', to='employer_dashboard.interviewer')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='employer_dashboard.interviewfeedback')),
            ],
            options={
                'db_table': 'employer_feedback_reminders',
            },
        ),
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_data', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_templates', to='employer_dashboard.employerprofile')),
            ],
            options={
                'db_table': 'employer_feedback_templates',
                'indexes': [models.Index(fields=['employer', 'is_active'], name='employer_fe_employe_eb6842_idx'), models.Index(fields=['is_default', 'is_active'], name='employer_fe_is_defa_e64439_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['employer', 'interview_status'], name='employer_in_employe_94c9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['candidate', 'interview_date'], name='employer_in_candida_1de198_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['interviewer', 'submitted_at'], name='employer_in_intervi_6eb18e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['interview_status', 'created_at'], name='employer_in_intervi_190418_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewfeedback',
            index=models.Index(fields=['overall_rating', 'interview_date'], name='employer_in_overall_72fe4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AddIndex(
            model_name='feedbackreminder',
            index=models.Index(fields=['scheduled_at', 'is_sent'], name='employer_fe_schedul_8fd34e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackreminder',
            index=models.Index(fields=['interviewer', 'is_sent'], name='employer_fe_intervi_c72950_idx'),
        ),
    ]
