# Generated by Django 5.2.3 on 2025-10-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employer_dashboard",
            "0005_interviewfeedback_feedbackreminder_feedbacktemplate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="github_profile_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="last_login_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="linkedin_profile_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="profile_completion_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="profile_picture_url",
            field=models.URLField(
                blank=True, help_text="Profile picture from social media"
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="social_media_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw social media profile data"
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_location",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
