# Generated by Django 5.2.3 on 2025-10-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer_dashboard", "0008_remove_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="bio",
            field=models.TextField(
                blank=True, default="", help_text="Company bio or introduction"
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_logo_url",
            field=models.URLField(blank=True, default="", help_text="Company logo URL"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="employer_introduction",
            field=models.TextField(
                blank=True, default="", help_text="Personal introduction from employer"
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="facebook_profile_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="instagram_profile_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Employer's profile picture stored in database",
                null=True,
                upload_to="employer_profiles/",
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="twitter_profile_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="additional_notes",
            field=models.TextField(
                blank=True, default="", help_text="Additional Notes or Instructions"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.TextField(blank=True, help_text="Benefits and Perks"),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(
                blank=True, default="", help_text="Company Name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("high_school", "High School"),
                    ("associate", "Associate Degree"),
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("phd", "PhD"),
                    ("any", "Any Education Level"),
                ],
                default="any",
                help_text="Required Education Level",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Employer's Bio or Company Introduction",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_email",
            field=models.EmailField(
                blank=True, default="", help_text="Employer's Email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_linkedin_url",
            field=models.URLField(
                blank=True, default="", help_text="Employer's LinkedIn Profile"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_logo",
            field=models.ImageField(
                blank=True,
                help_text="Custom employer logo for this job posting",
                null=True,
                upload_to="job_employer_logos/",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_logo_url",
            field=models.URLField(
                blank=True, default="", help_text="Employer logo URL"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Employer's Display Name",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Employer's Phone Number",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media handles (Twitter, Facebook, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer_website_url",
            field=models.URLField(
                blank=True, default="", help_text="Employer's Website"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level (0-1 years)"),
                    ("junior", "Junior (1-3 years)"),
                    ("mid", "Mid Level (3-5 years)"),
                    ("senior", "Senior (5-8 years)"),
                    ("lead", "Lead (8+ years)"),
                    ("executive", "Executive"),
                ],
                default="entry",
                help_text="Required Experience Level",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="language_proficiency",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Required Languages with proficiency levels",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_currency",
            field=models.CharField(
                blank=True, default="INR", help_text="Currency Code", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.JSONField(
                blank=True, default=list, help_text="Required Skills as JSON list"
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo stored in database",
                null=True,
                upload_to="company_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="contact_person",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="employer_name",
            field=models.CharField(
                default="", help_text="Employer's display name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="github_profile_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="industry_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="last_login_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="linkedin_profile_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="profile_picture_url",
            field=models.URLField(
                blank=True, default="", help_text="Profile picture from social media"
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Application Deadline", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="applications_count",
            field=models.IntegerField(default=0, help_text="Number of Applications"),
        ),
        migrations.AlterField(
            model_name="job",
            name="candidate_profile",
            field=models.TextField(blank=True, help_text="Ideal Candidate Profile"),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_email",
            field=models.EmailField(
                blank=True, help_text="Contact Email", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_preferences",
            field=models.JSONField(
                blank=True, default=list, help_text="Contact Preferences"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="department",
            field=models.CharField(blank=True, help_text="Department", max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(help_text="Job Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="designation",
            field=models.CharField(
                blank=True, help_text="Job Designation", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="education",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific Education Requirements",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                blank=True,
                help_text="Employment Type (On-site, Remote, Hybrid)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_max",
            field=models.IntegerField(
                default=0, help_text="Maximum Years of Experience"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_min",
            field=models.IntegerField(
                default=0, help_text="Minimum Years of Experience"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="gender_preference",
            field=models.CharField(
                blank=True, help_text="Gender Preference", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                blank=True, help_text="Industry Type", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="interview_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("virtual", "Virtual Interview"),
                    ("walkin", "Walk-in Interview"),
                    ("hybrid", "Hybrid"),
                ],
                default="",
                help_text="Interview Method",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("temporary", "Temporary"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                help_text="Job Type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(help_text="Job Location", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="notification_preferences",
            field=models.JSONField(
                blank=True, default=list, help_text="Notification Preferences"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="perks",
            field=models.TextField(blank=True, help_text="Additional Perks"),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True, help_text="Job Requirements"),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum Salary",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum Salary",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.TextField(
                blank=True, default="", help_text="Required Skills (comma separated)"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("closed", "Closed"),
                    ("draft", "Draft"),
                ],
                default="active",
                help_text="Job Status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(help_text="Job Title", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="urgency",
            field=models.CharField(
                choices=[("normal", "Normal"), ("urgent", "Urgent")],
                default="normal",
                help_text="Job Urgency",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="views_count",
            field=models.IntegerField(default=0, help_text="Number of Views"),
        ),
        migrations.AlterField(
            model_name="job",
            name="virtual_platform",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Virtual Interview Platform",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="walkin_address",
            field=models.TextField(
                blank=True, default="", help_text="Walk-in Interview Address"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "status"], name="employer_da_job_typ_61608b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["industry", "status"], name="employer_da_industr_69efa7_idx"
            ),
        ),
    ]
