# Generated by Django 5.2.3 on 2025-10-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employer_dashboard",
            "0009_employerprofile_bio_employerprofile_company_logo_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_update_from_linkedin", models.BooleanField(default=True)),
                ("auto_update_from_google", models.BooleanField(default=True)),
                ("auto_sync_company_info", models.BooleanField(default=True)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("connections", "Connections Only"),
                            ("verified", "Verified Users Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("show_contact_info", models.BooleanField(default=True)),
                ("show_company_size", models.BooleanField(default=True)),
                ("show_website", models.BooleanField(default=True)),
                ("show_social_media", models.BooleanField(default=True)),
                ("allow_profile_search", models.BooleanField(default=True)),
                ("notify_new_applications", models.JSONField(blank=True, default=list)),
                (
                    "notify_application_updates",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "notify_interview_scheduled",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "notify_interview_reminders",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "notify_candidate_messages",
                    models.JSONField(blank=True, default=list),
                ),
                ("notify_system_updates", models.JSONField(blank=True, default=list)),
                ("notify_security_alerts", models.JSONField(blank=True, default=list)),
                ("notify_billing_updates", models.JSONField(blank=True, default=list)),
                ("notify_feature_updates", models.JSONField(blank=True, default=list)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="instant",
                        max_length=20,
                    ),
                ),
                ("enable_quiet_hours", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(default="22:00")),
                ("quiet_hours_end", models.TimeField(default="08:00")),
                (
                    "quiet_hours_timezone",
                    models.CharField(default="UTC", max_length=50),
                ),
                ("require_2fa", models.BooleanField(default=False)),
                (
                    "backup_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("auto_logout_minutes", models.IntegerField(default=120)),
                ("require_ip_verification", models.BooleanField(default=False)),
                ("allowed_ip_addresses", models.JSONField(blank=True, default=list)),
                ("notify_new_login", models.BooleanField(default=True)),
                ("notify_suspicious_login", models.BooleanField(default=True)),
                ("enable_activity_logging", models.BooleanField(default=True)),
                ("enable_audit_trail", models.BooleanField(default=True)),
                ("data_retention_days", models.IntegerField(default=365)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                            ("purple", "Purple"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("custom_theme_colors", models.JSONField(blank=True, default=dict)),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                ("show_animations", models.BooleanField(default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("hi", "Hindi"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="MM/DD/YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12 Hour"), ("24h", "24 Hour")],
                        default="12h",
                        max_length=10,
                    ),
                ),
                (
                    "dashboard_layout",
                    models.CharField(
                        choices=[
                            ("grid", "Grid View"),
                            ("list", "List View"),
                            ("compact", "Compact View"),
                            ("detailed", "Detailed View"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                ("items_per_page", models.IntegerField(default=10)),
                ("default_job_view", models.CharField(default="active", max_length=20)),
                ("show_analytics_widgets", models.BooleanField(default=True)),
                ("widget_positions", models.JSONField(blank=True, default=dict)),
                (
                    "default_job_type",
                    models.CharField(default="full_time", max_length=50),
                ),
                (
                    "default_experience_level",
                    models.CharField(default="entry", max_length=50),
                ),
                (
                    "default_interview_method",
                    models.CharField(default="virtual", max_length=20),
                ),
                ("auto_close_expired_jobs", models.BooleanField(default=True)),
                ("auto_repost_expired_jobs", models.BooleanField(default=False)),
                ("require_cover_letter", models.BooleanField(default=False)),
                ("allow_anonymous_applications", models.BooleanField(default=False)),
                ("auto_acknowledge_applications", models.BooleanField(default=True)),
                ("application_deadline_days", models.IntegerField(default=30)),
                ("default_interview_duration", models.IntegerField(default=60)),
                ("default_interview_buffer", models.IntegerField(default=15)),
                ("auto_generate_meeting_links", models.BooleanField(default=True)),
                ("send_interview_reminders", models.BooleanField(default=True)),
                ("reminder_hours_before", models.JSONField(blank=True, default=list)),
                ("require_interview_feedback", models.BooleanField(default=True)),
                ("feedback_deadline_hours", models.IntegerField(default=24)),
                ("auto_send_feedback_reminders", models.BooleanField(default=True)),
                (
                    "default_feedback_template",
                    models.CharField(blank=True, max_length=255),
                ),
                ("enable_proxy_detection", models.BooleanField(default=True)),
                (
                    "proxy_detection_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("block_known_proxies", models.BooleanField(default=True)),
                ("block_datacenter_ips", models.BooleanField(default=False)),
                ("allowed_countries", models.JSONField(blank=True, default=list)),
                ("blocked_countries", models.JSONField(blank=True, default=list)),
                ("email_integration_enabled", models.BooleanField(default=False)),
                ("email_provider", models.CharField(blank=True, max_length=50)),
                ("email_api_key", models.CharField(blank=True, max_length=500)),
                ("calendar_integration_enabled", models.BooleanField(default=False)),
                ("calendar_provider", models.CharField(blank=True, max_length=50)),
                ("auto_create_calendar_events", models.BooleanField(default=False)),
                ("ats_integration_enabled", models.BooleanField(default=False)),
                ("ats_provider", models.CharField(blank=True, max_length=50)),
                ("ats_webhook_url", models.URLField(blank=True)),
                ("linkedin_integration_enabled", models.BooleanField(default=False)),
                ("linkedin_access_token", models.CharField(blank=True, max_length=500)),
                ("auto_post_jobs_linkedin", models.BooleanField(default=False)),
                ("preferred_currency", models.CharField(default="USD", max_length=3)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("auto_renew_subscriptions", models.BooleanField(default=True)),
                ("billing_notifications", models.BooleanField(default=True)),
                ("allow_data_analytics", models.BooleanField(default=True)),
                ("share_anonymous_usage", models.BooleanField(default=True)),
                ("allow_marketing_emails", models.BooleanField(default=False)),
                ("allow_partner_communications", models.BooleanField(default=False)),
                ("candidate_data_retention_days", models.IntegerField(default=730)),
                (
                    "auto_delete_rejected_applications",
                    models.BooleanField(default=False),
                ),
                ("allow_candidate_data_export", models.BooleanField(default=True)),
                ("api_access_enabled", models.BooleanField(default=False)),
                ("api_rate_limit", models.IntegerField(default=1000)),
                ("webhook_notifications", models.BooleanField(default=False)),
                ("custom_job_fields", models.JSONField(blank=True, default=list)),
                (
                    "custom_application_fields",
                    models.JSONField(blank=True, default=list),
                ),
                ("custom_candidate_fields", models.JSONField(blank=True, default=list)),
                ("auto_backup_enabled", models.BooleanField(default=True)),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="employer_dashboard.employerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employer Settings",
                "verbose_name_plural": "Employer Settings",
                "db_table": "employer_settings",
            },
        ),
    ]
