# Generated by Django 5.2.3 on 2025-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_dashboard', '0010_employersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ats_keywords',
            field=models.TextField(blank=True, default='', help_text='ATS Keywords for resume matching'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_benefits',
            field=models.TextField(blank=True, default='', help_text='Company-wide benefits and culture description'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, default='', help_text='Company size for this job posting', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='Frequently Asked Questions as JSON list'),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_process_stages',
            field=models.JSONField(blank=True, default=list, help_text='Hiring process stages'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_brief',
            field=models.TextField(blank=True, default='', help_text='Brief overview of the job'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list, help_text='Job Responsibilities as JSON array'),
        ),
        migrations.AddField(
            model_name='job',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list, help_text='Screening questions for applicants'),
        ),
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Benefits and Perks as JSON array'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_logo',
            field=models.ImageField(blank=True, help_text='Custom employer logo for this job posting (uploaded file)', null=True, upload_to='job_employer_logos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_logo_url',
            field=models.URLField(blank=True, default='', help_text='Employer logo URL (external link)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='perks',
            field=models.TextField(blank=True, default='', help_text='Additional Perks (deprecated - use benefits)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='Job Requirements as JSON array'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Required Skills as JSON array'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text='Required Skills (deprecated - use skills)'),
        ),
    ]
