# Generated by Django 5.2.3 on 2025-11-04 13:16

from django.db import migrations
import json


def fix_invalid_json_fields(apps, schema_editor):
    """Fix invalid JSON fields in Job model"""
    Job = apps.get_model('employer_dashboard', 'Job')
    
    # List of JSON fields that should be lists
    list_fields = [
        'responsibilities', 'requirements', 'benefits', 'faqs', 
        'screening_questions', 'hiring_process_stages', 'skills',
        'skills_required', 'language_proficiency', 'contact_preferences',
        'notification_preferences'
    ]
    
    # List of JSON fields that should be dicts
    dict_fields = ['employer_social_media']
    
    for job in Job.objects.all():
        updated = False
        
        # Fix list fields
        for field_name in list_fields:
            field_value = getattr(job, field_name)
            if field_value == '' or field_value is None:
                setattr(job, field_name, [])
                updated = True
            elif isinstance(field_value, str):
                try:
                    # Try to parse as JSON
                    parsed = json.loads(field_value)
                    if not isinstance(parsed, list):
                        setattr(job, field_name, [])
                        updated = True
                except (json.JSONDecodeError, TypeError):
                    # If parsing fails, set to empty list
                    setattr(job, field_name, [])
                    updated = True
        
        # Fix dict fields
        for field_name in dict_fields:
            field_value = getattr(job, field_name)
            if field_value == '' or field_value is None:
                setattr(job, field_name, {})
                updated = True
            elif isinstance(field_value, str):
                try:
                    # Try to parse as JSON
                    parsed = json.loads(field_value)
                    if not isinstance(parsed, dict):
                        setattr(job, field_name, {})
                        updated = True
                except (json.JSONDecodeError, TypeError):
                    # If parsing fails, set to empty dict
                    setattr(job, field_name, {})
                    updated = True
        
        if updated:
            job.save()


def reverse_fix_invalid_json_fields(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("employer_dashboard", "0011_job_ats_keywords_job_company_benefits_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_json_fields, reverse_fix_invalid_json_fields),
    ]
