# Generated by Django 5.2.3 on 2025-12-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_dashboard", "0011_remove_candidatesearchprofile_strengths_and_more"),
        ("employer_dashboard", "0012_auto_20251104_1846"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AddField(
            model_name="job",
            name="company_slug",
            field=models.SlugField(
                blank=True, help_text="Company name slug for URL", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_number",
            field=models.IntegerField(
                default=0, help_text="Sequential job number for this company"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="title_slug",
            field=models.SlugField(
                blank=True, help_text="Job title slug for URL", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="ats_score",
            field=models.FloatField(default=0.0, help_text="ATS match score 0-100"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="employee_dashboard.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="matching_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Keywords matched from job requirements",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="missing_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Important keywords missing from resume",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_file_size",
            field=models.IntegerField(default=0, help_text="File size in bytes"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="screening_answers",
            field=models.JSONField(
                blank=True, default=list, help_text='[{"question": "", "answer": ""}]'
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="viewed_by_employer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="candidate_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="application_resumes/"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "-ats_score"], name="employer_da_job_id_249762_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["employee", "-applied_at"],
                name="employer_da_employe_caa0a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "-applied_at"], name="employer_da_status_df013f_idx"
            ),
        ),
    ]
