# Generated by Django 5.2.4 on 2025-10-08 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_score_threshold', models.FloatField(default=70.0)),
                ('max_analyses_per_day', models.IntegerField(default=10)),
                ('premium_max_analyses', models.IntegerField(default=50)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('model_accuracy', models.FloatField(default=85.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ATS Settings',
                'db_table': 'ats_settings',
            },
        ),
        migrations.CreateModel(
            name='ATSKeywordLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('role_category', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list, help_text='List of relevant keywords')),
                ('importance_score', models.IntegerField(default=1, help_text='Keyword importance (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ATS Keyword Library',
                'verbose_name_plural': 'ATS Keyword Libraries',
                'db_table': 'ats_keyword_library',
                'unique_together': {('industry', 'role_category')},
            },
        ),
        migrations.CreateModel(
            name='ATSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0.0, help_text='ATS compatibility score (0-100)')),
                ('keywords_optimized', models.JSONField(default=list, help_text='List of optimized keywords')),
                ('last_scan_date', models.DateTimeField(auto_now=True)),
                ('scan_count', models.IntegerField(default=0)),
                ('usage_type', models.CharField(choices=[('RESUME_OPTIMIZATION', 'Resume Optimization'), ('JOB_DESCRIPTION', 'Job Description Analysis')], default='RESUME_OPTIMIZATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATS Profile',
                'verbose_name_plural': 'ATS Profiles',
                'db_table': 'ats_profiles',
            },
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('RESUME', 'Resume Analysis'), ('JOB_DESCRIPTION', 'Job Description Analysis'), ('COVER_LETTER', 'Cover Letter Analysis')], max_length=20)),
                ('document_text', models.TextField()),
                ('document_file', models.FileField(blank=True, null=True, upload_to='ats_documents/')),
                ('score', models.FloatField(help_text='ATS compatibility score (0-100)')),
                ('feedback', models.JSONField(default=dict, help_text='Detailed feedback and suggestions')),
                ('keywords_found', models.JSONField(default=list)),
                ('keywords_missing', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list, help_text='List of improvement suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ats_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ats.atsprofile')),
            ],
            options={
                'verbose_name': 'ATS Analysis',
                'verbose_name_plural': 'ATS Analyses',
                'db_table': 'ats_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
